version: '3.8'

services:
  my_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_app_container
    restart: always
    volumes:
      - .:/app
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility